---
proxy-providers:
  Premium:
    type: file
    path: "./proxy_provider/xl-vidio.premium.yml"
    interface-name: usb0
    health-check:
      url: http://www.gstatic.com/generate_204
      enable: true
      interval: 30
  Free:
    type: file
    path: "./proxy_provider/xl-vidio.free.yml"
    interface-name: usb0
    health-check:
      url: http://www.gstatic.com/generate_204
      enable: true
      interval: 30

proxy-groups:
  - name: Load Balance
    type: load-balance
    strategy: round-robin
    disable-udp: false
    proxies:
      - Multi WAN
      - Inject Balance
    url: http://www.gstatic.com/generate_204
    interval: 30

  - name: Inject Balance
    type: load-balance
    strategy: round-robin
    disable-udp: false
    use:
      - Premium
      - Free
    url: http://www.gstatic.com/generate_204
    interval: 30

  - name: Multi WAN
    type: load-balance
    strategy: round-robin
    disable-udp: false
    proxies:
      - WAN (usb0)
      - WAN (usb1)
    url: http://www.gstatic.com/generate_204
    interval: 30

  - name: Inject
    type: select
    disable-udp: false
    use:
      - Premium
      - Free
    proxies:
      - Inject Balance
    url: http://www.gstatic.com/generate_204
    interval: 30

  - name: Direct
    type: select
    disable-udp: false
    proxies:
      - Multi WAN
      - WAN (usb0)
      - WAN (usb1)
      - Inject
      - Inject Balance
      - Load Balance
    url: http://www.gstatic.com/generate_204
    interval: 30

  - name: Streaming
    type: select
    disable-udp: false
    proxies:
      - Direct
      - Inject
      - Inject Balance
      - Load Balance
      - Multi WAN
    url: http://www.gstatic.com/generate_204
    interval: 30

  - name: Sosmed
    type: select
    disable-udp: false
    proxies:
      - Direct
      - Inject
      - Inject Balance
      - Load Balance
      - Multi WAN
    url: http://www.gstatic.com/generate_204
    interval: 30

  - name: Umum
    type: select
    disable-udp: false
    proxies:
      - Direct
      - Inject
      - Load Balance
      - Inject Balance
      - Multi WAN
    url: http://www.gstatic.com/generate_204
    interval: 30

  - name: Indonesia
    type: select
    disable-udp: false
    proxies:
      - Direct
      - Inject
      - Inject Balance
      - Load Balance
      - Multi WAN
    url: http://www.gstatic.com/generate_204
    interval: 30

  - name: PortGames
    type: select
    disable-udp: false
    proxies:
      - Direct
      - Inject
      - Multi WAN
      - Inject Balance
      - Load Balance
    url: http://www.gstatic.com/generate_204
    interval: 30

  - name: Gaming
    type: select
    disable-udp: false
    proxies:
      - Direct
      - Inject
      - Multi WAN
      - Inject Balance
      - Load Balance
    url: http://www.gstatic.com/generate_204
    interval: 30

  - name: Ads
    type: select
    disable-udp: false
    proxies:
      - Direct
      - Inject
      - Inject Balance
      - Load Balance
      - Multi WAN
      - REJECT
    url: http://www.gstatic.com/generate_204
    interval: 30

  - name: Porn
    type: select
    disable-udp: false
    proxies:
      - Inject Balance
      - Load Balance
      - Multi WAN
      - Direct
      - Inject
    url: http://www.gstatic.com/generate_204
    interval: 30

  - name: Speedtest-CLI
    type: select
    disable-udp: false
    proxies:
      - Inject Balance
    use:
      - Premium
      - Free
    url: http://www.gstatic.com/generate_204
    interval: 30

  - name: Speedtest
    type: select
    disable-udp: false
    proxies:
      - Speedtest-CLI
      - Inject Balance
      - Load Balance
      - Multi WAN
      - Direct
      - Inject
    use:
      - Premium
      - Free
    url: http://www.gstatic.com/generate_204
    interval: 30

  - name: WAN (usb0)
    type: fallback
    lazy: true
    disable-udp: false
    interface-name: usb0
    proxies:
      - DIRECT
    url: http://www.gstatic.com/generate_204
    interval: 30

  - name: WAN (usb1)
    type: fallback
    lazy: true
    disable-udp: false
    interface-name: usb1
    proxies:
      - DIRECT
    url: http://www.gstatic.com/generate_204
    interval: 30

redir-port: 7892
port: 7890
socks-port: 7891
mixed-port: 7893
mode: rule
log-level: debug
allow-lan: true
external-controller: 0.0.0.0:9090
secret: "nsmlesleep"
bind-address: "*"
external-ui: "/ui/yacd"
experimental:
  ignore-resolve-fail: true
dns:
  enable: true
  ipv6: true
  enhanced-mode: fake-ip
  listen: 0.0.0.0:7874
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter:
    - "*.lan"
    - "*.localdomain"
    - "*.example"
    - "*.invalid"
    - "*.localhost"
    - "*.test"
    - "*.local"
    - "*.home.arpa"
    - time.*.com
    - time.*.gov
    - time.*.edu.cn
    - time.*.apple.com
    - time1.*.com
    - time2.*.com
    - time3.*.com
    - time4.*.com
    - time5.*.com
    - time6.*.com
    - time7.*.com
    - ntp.*.com
    - ntp1.*.com
    - ntp2.*.com
    - ntp3.*.com
    - ntp4.*.com
    - ntp5.*.com
    - ntp6.*.com
    - ntp7.*.com
    - "*.time.edu.cn"
    - "*.ntp.org.cn"
    - "+.pool.ntp.org"
    - time1.cloud.tencent.com
    - music.163.com
    - "*.music.163.com"
    - "*.126.net"
    - musicapi.taihe.com
    - music.taihe.com
    - songsearch.kugou.com
    - trackercdn.kugou.com
    - "*.kuwo.cn"
    - api-jooxtt.sanook.com
    - api.joox.com
    - joox.com
    - y.qq.com
    - "*.y.qq.com"
    - streamoc.music.tc.qq.com
    - mobileoc.music.tc.qq.com
    - isure.stream.qqmusic.qq.com
    - dl.stream.qqmusic.qq.com
    - aqqmusic.tc.qq.com
    - amobile.music.tc.qq.com
    - "*.xiami.com"
    - "*.music.migu.cn"
    - music.migu.cn
    - "+.msftconnecttest.com"
    - "+.msftncsi.com"
    - msftconnecttest.com
    - msftncsi.com
    - localhost.ptlogin2.qq.com
    - localhost.sec.qq.com
    - "+.srv.nintendo.net"
    - "*.n.n.srv.nintendo.net"
    - "+.stun.playstation.net"
    - xbox.*.*.microsoft.com
    - "*.*.xboxlive.com"
    - xbox.*.microsoft.com
    - xnotify.xboxlive.com
    - "+.battlenet.com.cn"
    - "+.wotgame.cn"
    - "+.wggames.cn"
    - "+.wowsgame.cn"
    - "+.wargaming.net"
    - proxy.golang.org
    - stun.*.*
    - stun.*.*.*
    - "+.stun.*.*"
    - "+.stun.*.*.*"
    - "+.stun.*.*.*.*"
    - "+.stun.*.*.*.*.*"
    - heartbeat.belkin.com
    - "*.linksys.com"
    - "*.linksyssmartwifi.com"
    - "*.router.asus.com"
    - mesu.apple.com
    - swscan.apple.com
    - swquery.apple.com
    - swdownload.apple.com
    - swcdn.apple.com
    - swdist.apple.com
    - lens.l.google.com
    - stun.l.google.com
    - "+.nflxvideo.net"
    - "*.square-enix.com"
    - "*.finalfantasyxiv.com"
    - "*.ffxiv.com"
    - "*.ff14.sdo.com"
    - ff.dorado.sdo.com
    - "*.mcdn.bilivideo.cn"
    - "+.media.dssott.com"
    - time-ios.apple.com
    - shark007.net
  fallback-filter:
    geoip: true
    geoip-code: ID
    ipcidr:
      - 0.0.0.0/8
      - 10.0.0.0/8
      - 100.64.0.0/10
      - 127.0.0.0/8
      - 169.254.0.0/16
      - 172.16.0.0/12
      - 192.0.0.0/24
      - 192.0.2.0/24
      - 192.88.99.0/24
      - 192.168.0.0/16
      - 198.18.0.0/15
      - 198.51.100.0/24
      - 203.0.113.0/24
      - 224.0.0.0/4
      - 240.0.0.0/4
      - 255.255.255.255/32
    domain:
      - "+.google.com"
      - "+.facebook.com"
      - "+.youtube.com"
      - "+.githubusercontent.com"
      - "+.googlevideo.com"
      - "+.msftconnecttest.com"
      - "+.msftncsi.com"
      - msftconnecttest.com
      - msftncsi.com
      - "+.*"
  default-nameserver:
    - 8.8.8.8
    - 8.8.4.4
    - 1.1.1.1
    - 1.0.0.1
    - 9.9.9.9
    - 149.112.112.112
    - 208.67.222.222
    - 208.67.220.220
    - 185.228.168.9
    - 185.228.169.168
    - 76.76.2.0
    - 76.76.10.0
    - 94.140.14.140
    - 94.140.14.141
    - 172.105.216.54
  nameserver:
    - 1.1.1.1
    - 8.8.8.8
    - 9.9.9.9
  fallback:
    - 1.1.1.1
    - 8.8.8.8
    - 9.9.9.9
profile:
  store-selected: true
  store-fakeip: true
  store-fake-ip: true
rules:
  - IP-CIDR,198.18.0.1/16,REJECT,no-resolve
  - DST-PORT,22,Direct
  - RULE-SET,LanCIDR,DIRECT,no-resolve
  - RULE-SET,FalsePositive,Umum
  - RULE-SET,Malicious,REJECT
  - RULE-SET,MaliciousIP,REJECT
  - RULE-SET,PersonalAds,Ads
  - RULE-SET,BasicAds,Ads
  - RULE-SET,Hijacking,Ads
  - RULE-SET,Privacy,Ads
  - RULE-SET,Porn,Porn
  # - RULE-SET,Nsfw,Porn
  - RULE-SET,Direct,Direct
  - SCRIPT,Speedtest,Speedtest
  - RULE-SET,Playstore,Umum
  - RULE-SET,DisneyPlus,Indonesia
  - RULE-SET,Netflix,Indonesia
  - RULE-SET,Indonesia,Indonesia
  - RULE-SET,Hbo,Indonesia
  - RULE-SET,HboAsia,Indonesia
  - RULE-SET,HboHk,Indonesia
  - RULE-SET,HboUsa,Indonesia
  - RULE-SET,Streaming,Streaming
  - RULE-SET,Iqiyi,Streaming
  - RULE-SET,IqiyiInternational,Streaming
  - RULE-SET,PrimeVideo,Streaming
  - RULE-SET,Twitch,Streaming
  - RULE-SET,Youtube,Streaming
  - RULE-SET,Sosmed,Sosmed
  - RULE-SET,Line,Sosmed
  - RULE-SET,Metaverse,Sosmed
  - RULE-SET,Tiktok,Sosmed
  - RULE-SET,Twitter,Sosmed
  - RULE-SET,Telegram,Sosmed
  - RULE-SET,TelegramCIDR,Sosmed
  - RULE-SET,VideoConferences,Streaming
  - RULE-SET,PortGames,PortGames
  - SCRIPT,TCPgames,PortGames
  - SCRIPT,UDPgames,PortGames
  - RULE-SET,Gaming,Gaming
  - RULE-SET,Games,Gaming
  - RULE-SET,Discord,Gaming
  - RULE-SET,Umum,Umum
  - MATCH,GLOBAL
tun:
  enable: true
  stack: system
  auto-route: false
  auto-detect-interface: false
  dns-hijack:
    - tcp://any:53
tproxy-port: 7895
script:
  shortcuts:
    TCPgames: network == 'tcp' and dst_port not in [21, 22, 23, 53, 80, 123, 143, 194, 443, 465, 587, 853, 993, 995, 998, 2052, 2053, 2082, 2083, 2086, 2095, 2096, 5222, 5228, 5229, 5230, 8080, 8443, 8880, 8883, 8888, 8889]
    UDPgames: network == 'udp' and dst_port not in [21, 22, 23, 53, 80, 123, 143, 194, 443, 465, 587, 853, 993, 995, 998, 2052, 2053, 2082, 2083, 2086, 2095, 2096, 5222, 5228, 5229, 5230, 8080, 8443, 8880, 8883, 8888, 8889]
    Speedtest: network == "tcp" and match_provider("Speedtest")
rule-providers:
  Direct:
    type: file
    behavior: classical
    path: "./rule_provider/direct.rule"
  Umum:
    type: file
    behavior: classical
    path: "./rule_provider/umum.rule"
  PortGames:
    type: file
    behavior: classical
    path: "./rule_provider/games-port.rule"
  VideoConferences:
    type: file
    behavior: classical
    path: "./rule_provider/video-conferences.rule"
  Indonesia:
    type: file
    behavior: classical
    path: "./rule_provider/indonesia.rule"
  Sosmed:
    type: file
    behavior: classical
    path: "./rule_provider/sosmed.rule"
  Streaming:
    type: file
    behavior: classical
    path: "./rule_provider/streaming.rule"
  Gaming:
    type: file
    behavior: classical
    path: "./rule_provider/gaming.rule"
  Speedtest:
    type: file
    behavior: classical
    path: "./rule_provider/speedtest.rule"
  Discord:
    type: file
    behavior: classical
    path: "./rule_provider/discord.rule"
  Hijacking:
    type: file
    behavior: classical
    path: "./rule_provider/hijacking.rule"
  Privacy:
    type: file
    behavior: classical
    path: "./rule_provider/privacy.rule"
  BasicAds:
    type: file
    behavior: domain
    path: "./rule_provider/basic-ads.rule"
  PersonalAds:
    type: file
    behavior: classical
    path: "./rule_provider/personal-ads.rule"
  Malicious:
    type: file
    behavior: domain
    path: "./rule_provider/malicious.rule"
  MaliciousIP:
    type: file
    behavior: ipcidr
    path: "./rule_provider/malicious-ip.rule"
  FalsePositive:
    type: file
    behavior: classical
    path: "./rule_provider/false-positive.rule"
  Porn:
    type: file
    behavior: domain
    path: "./rule_provider/porn.rule"
  # Nsfw:
  #   type: file
  #   behavior: domain
  #   path: "./rule_provider/nsfw.rule"
  LanCIDR:
    type: file
    behavior: ipcidr
    path: "./rule_provider/lan-cidr.rule"
  TelegramCIDR:
    type: file
    behavior: ipcidr
    path: "./rule_provider/telegram-cidr.rule"
  Telegram:
    type: file
    behavior: domain
    path: "./rule_provider/telegram.rule"
  DisneyPlus:
    type: file
    behavior: classical
    path: "./rule_provider/disney-plus.rule"
  Games:
    type: file
    behavior: domain
    path: "./rule_provider/games.rule"
  Hbo:
    type: file
    behavior: classical
    path: "./rule_provider/hbo.rule"
  HboAsia:
    type: file
    behavior: classical
    path: "./rule_provider/hbo-asia.rule"
  HboHk:
    type: file
    behavior: classical
    path: "./rule_provider/hbo-hk.rule"
  HboUsa:
    type: file
    behavior: classical
    path: "./rule_provider/hbo-usa.rule"
  Iqiyi:
    type: file
    behavior: classical
    path: "./rule_provider/iqiyi.rule"
  IqiyiInternational:
    type: file
    behavior: classical
    path: "./rule_provider/iqiyi-international.rule"
  Line:
    type: file
    behavior: domain
    path: "./rule_provider/line.rule"
  Metaverse:
    type: file
    behavior: domain
    path: "./rule_provider/metaverse.rule"
  Netflix:
    type: file
    behavior: domain
    path: "./rule_provider/netflix.rule"
  PrimeVideo:
    type: file
    behavior: domain
    path: "./rule_provider/prime-video.rule"
  Playstore:
    type: file
    behavior: domain
    path: "./rule_provider/playstore.rule"
  Tiktok:
    type: file
    behavior: domain
    path: "./rule_provider/tiktok.rule"
  Twitch:
    type: file
    behavior: domain
    path: "./rule_provider/twitch.rule"
  Twitter:
    type: file
    behavior: domain
    path: "./rule_provider/twitter.rule"
  Youtube:
    type: file
    behavior: domain
    path: "./rule_provider/youtube.rule"
ipv6: true
